version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - TEST_AWS_ACCOUNT_ID=${AWS_ACCESS_KEY_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY}
      - EDGE_PORT=4566
      - DOCKER_HOST=unix:///var/run/docker.sock
      # - SERVICES=sqs,sns
      - DEBUG=${LOCALSTACK_DEBUG-}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"